#!/bin/bash

#SBATCH --partition=main
##SBATCH --gres=gpu:p100:1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32GB
#SBATCH --time=45:00:00
#SBATCH --account=tbrun_769
#SBATCH --output=/project/tbrun_769/qdec/logs/%j.out

module purge
module load gcc/8.3.0
module load cuda/11.2.0
module load anaconda3

eval "$(conda shell.bash hook)"

conda activate /project/tbrun_769/envs/qdec
python3 source/alanka_driver.py n
